[project]
name = 'ProofOfAudit'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.proof-of-audit]
path = 'contracts/proof-of-audit.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
